"use client";

import { useEffect, useState } from "react";
import { getMyOrders } from "@/lib/orders";
import { getTransferByOrder, confirmTransfer } from "@/lib/transfers";
import { useAuth } from "@/lib/AuthContext";
import { formatPKR, formatEventDate } from "@/lib/utils";
import StatusBadge from "@/components/StatusBadge";
import RequireAuth from "@/components/RequireAuth";
import TransferModal from "@/components/TransferModal";
import { OrderItem, TicketTransfer } from "@/types";

export default function BuyerDashboardPage() {
  return (
    <RequireAuth>
      <BuyerDashboard />
    </RequireAuth>
  );
}

function BuyerDashboard() {
  const { user } = useAuth();
  const [orders, setOrders] = useState<OrderItem[]>([]);
  const [loading, setLoading] = useState(true);

  // Selected Transfer Modal State
  const [selectedTransfer, setSelectedTransfer] = useState<TicketTransfer | null>(null);
  const [activeOrder, setActiveOrder] = useState<OrderItem | null>(null);
  const [modalOpen, setModalOpen] = useState(false);
  const [loadingTransferId, setLoadingTransferId] = useState<string | null>(null);

  async function loadOrders() {
    try {
      const all = await getMyOrders();
      setOrders(all.filter((o) => o.buyer?.id === user?.id));
    } catch (err) {
      console.error("Failed to load orders", err);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    if (user) loadOrders();
  }, [user]);

  async function handleOpenTransfer(order: OrderItem) {
    setLoadingTransferId(order.id);
    setActiveOrder(order);
    try {
      const transfer = await getTransferByOrder(order.id);
      if (transfer) {
        setSelectedTransfer(transfer);
        setModalOpen(true);
      } else {
        alert("No transfer generated by seller yet.");
      }
    } catch (err) {
      alert("Failed to load ticket transfer details.");
    } finally {
      setLoadingTransferId(null);
    }
  }

  async function handleConfirmReceipt() {
    if (!activeOrder) return;
    await confirmTransfer(activeOrder.id);
    await loadOrders(); // Refresh order list
    const updated = await getTransferByOrder(activeOrder.id);
    if (updated) setSelectedTransfer(updated);
  }

  return (
    <div className="mx-auto max-w-4xl px-5 py-12">
      <div className="mb-8">
        <p className="text-[11px] font-stub uppercase tracking-widest text-muted mb-2">
          Purchaser Portal
        </p>
        <h1 className="font-display font-bold text-3xl">My Orders & Tickets</h1>
      </div>

      {loading ? (
        <div className="text-center py-16 text-muted text-sm flex items-center justify-center gap-2">
          <span className="w-4 h-4 border-2 border-ink border-t-transparent rounded-full animate-spin" />
          Loading orders...
        </div>
      ) : orders.length === 0 ? (
        <div className="text-center py-16 bg-white border border-line rounded-xl p-8">
          <p className="font-display font-bold text-lg mb-1">No orders found</p>
          <p className="text-muted text-sm">You haven&apos;t purchased any tickets yet.</p>
        </div>
      ) : (
        <div className="flex flex-col gap-4">
          {orders.map((o) => {
            const hasTransfer = o.status === "transferred" || o.status === "completed";
            return (
              <div
                key={o.id}
                className="flex flex-col sm:flex-row sm:items-center justify-between border border-line rounded-xl bg-white p-5 gap-4 shadow-xs hover:shadow-sm transition-shadow"
              >
                <div>
                  <div className="flex items-center gap-2 mb-1">
                    <span className="font-display font-semibold text-lg text-ink">
                      {o.ticketListing?.section ?? "Ticket Listing"}
                    </span>
                    <StatusBadge status={o.status} />
                  </div>
                  <p className="text-sm text-muted">
                    {o.ticketListing?.seatInfo} · Seller: {o.seller?.name}
                  </p>
                  <p className="text-xs text-muted/70 mt-1 font-stub uppercase">
                    Ordered: {formatEventDate(o.createdAt)} · Escrow: {o.escrowStatus}
                  </p>
                </div>

                <div className="flex items-center justify-between sm:justify-end gap-4 border-t sm:border-t-0 pt-3 sm:pt-0 border-line">
                  <div className="text-right">
                    <span className="text-xs text-muted block">Total Paid</span>
                    <span className="font-display font-bold text-lg text-ink">
                      {formatPKR(o.amount + o.platformFee)}
                    </span>
                  </div>

                  {hasTransfer && (
                    <button
                      onClick={() => handleOpenTransfer(o)}
                      disabled={loadingTransferId === o.id}
                      className="font-semibold text-xs bg-ink text-paper rounded-lg px-4 py-2.5 hover:bg-stamp hover:text-ink transition-colors shadow-xs"
                    >
                      {loadingTransferId === o.id ? "Loading Pass..." : "View Ticket / QR Code"}
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Ticket Transfer Modal */}
      <TransferModal
        isOpen={modalOpen}
        onClose={() => setModalOpen(false)}
        transfer={selectedTransfer}
        onConfirmReceipt={handleConfirmReceipt}
        isBuyer={true}
      />
    </div>
  );
}
